version: "3.8"

services:
  server:
    image: notes_server_wuchuheng_com:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    working_dir: /springBoot
    container_name: notesServer
    command: [
        "java",
        "-jar",
        "server-0.0.1-SNAPSHOT.jar",
        "--spring.profiles.active=prod"
    ]